### ISSUE TITLE
Add vignette?

### ISSUE THREAD

**Issue by richelbilderbeek** [TheoPannetier/comrad#22]
Salut @TheoPannetier,

I checked this package and I am missing a vignette that illustrates what the package does. Do you consider adding it?

Cheers, Richel

**Comment by TheoPannetier** [comment]
Hoi @richelbilderbeek, thanks for the suggestion!
I will write a vignette just before or just after releasing 1.0, which is close by now!
But first I need to go through a well-overdue round of tests.

Cheers
